### ISSUE TITLE
Support for Image storage

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/Storage-service#2]
# Feature - Server. 

### Implement the following API's in FAST API app. 
 
- [x] #3
        URL: /upload
        Method: POST
        Functionality: Accepts one or multiple image files and their respective keys (optional), saves the images, and stores metadata in SQLite.

- [x] #4
        URL: /retrieve/{key}
        Method: GET
        Functionality: Retrieves either a single image or its metadata based on the provided key.

- [x] #5
        URL: /update/{key}
        Method: PUT
        Functionality: Updates/Appends with new set of images or adds to the existing.

- [x] #6
        URL: /delete/{key}
        Method: DELETE
        Functionality: Deletes a single image and its metadata based on the provided key.

# Acceptance Criteria

- [x] Unit Tests

**Comment by noobed-max** [comment]
updated the reposity [https://github.com/noobed-max/Temp_storageService_cheta/tree/main](https://github.com/noobed-max/Temp_storageService_cheta/tree/main)
with main.py and crud.py and added git ignore

**Comment by noobed-max** [comment]
updated the main.py code to accept key and database name

**Comment by noobed-max** [comment]
issues in https://github.com/noobed-max/Temp_storageService_cheta/tree/main
![image](https://github.com/cia-labs/Storage-service/assets/146673372/eccb91d3-a7bb-4eef-90e5-e0cd91a86938)
![image](https://github.com/cia-labs/Storage-service/assets/146673372/e5d2dbb4-aa15-481b-b3a7-3905cde0e274)

Issue1:
same images and keys can be used multiples times (they do get assigned different id but the problem persists
as you can see in the SS the databse has two images with same keys but while executing get in fastapi over the key it retrieves the first key and image in database
Issue2:
Can only upload one file at a time

**Comment by noobed-max** [comment]
want to fix>
>>create a single db file for all metadata 
>> be able to upload multiple files/images either folder or zip etc
>>ask for key {optional}
>>mkdir key_dump path where all files and images are stored and can be modified
>>be able to provide GET for multiple files and images at once from the key which gets the path from the storage..........

**Comment by noobed-max** [comment]
[https://github.com/noobed-max/Temp_storageService_cheta/tree/main](https://github.com/noobed-max/Temp_storageService_cheta/tree/main)

- [x] create directory with key and store files 
- [x] auto generate key
- [ ] upload multiples files
- [x] separate db table if user wishes 
- [x] upload endpoint done
- [x] check if key exist in the table
- [ ] Retrieve multiples files
- [x] check separate db table if user wishes 
- [x] Retrieve endpoint done
