### ISSUE TITLE
Change key generation logic

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/Storage-service#28]
### Overview
Implement key generation logic as an incremental unsigned integer. Currently it's a random generator. The probability of getting the same key exists. 

### Implementation details
Maintain a thread safe unsigned integer variable in memory which will be incremented upon every write request.

**Comment by takuabonn** [comment]
I would like to try this problem.
I would like to be assigned this task.

**Comment by takuabonn** [comment]
hi, @Tejas-ChandraShekarRaju 
この問題を試してみたいと思います。
私はこの任務を任されたいと思っています。

**Comment by Tejas-ChandraShekarRaju** [comment]
@takuabonn Sure. 

Here’s a link for setup doc https://github.com/cia-labs/Storage-service/blob/main/docs.md. Let us know if you have any doubts.

**Comment by takuabonn** [comment]
hi, @Tejas-ChandraShekarRaju 

from current generate_random_string to change below implement.
```
import threading

class IncrementalIDGenerator:
    def __init__(self):
        self.lock = threading.Lock()
        self.counter = 0

    def generate_id(self):
        with self.lock:
            self.counter += 1
            return self.counter
```

**Comment by Tejas-ChandraShekarRaju** [comment]
Hey @takuabonn good initial analysis. But here's what else you have to consider. 

1. Inside init - self.Counter should be taken from Sqllite3. The case here is when the server reboots the counter shouldn't start from 0, you should query the count value from Sqllite3. 
2. Create a table in Sqllite3 key_counter and every write request should auto increment the count and use the same count. 
3. This way our count value is persistent and every time the server reboots we'll have the latest value. 
 

Let me know if you have any doubts.

**Comment by takuabonn** [comment]
hi,@Tejas-ChandraShekarRaju 
Indeed, I was missing the part you pointed out.
And to make it more unique
Should I use something like the following ?
Timestamp - integer part

**Comment by Tejas-ChandraShekarRaju** [comment]
Hey, Let’s not complicate it. We’ll use a 64 bit unsigned Integer which is big enough to be unique. Check if sqllite3 supports this else store it as a string in the table. Let me know if you have any further doubts.

**Comment by takuabonn** [comment]
hi, @Tejas-ChandraShekarRaju 
Thanks for assigning it to me.
It seems that sqlite3 only has signed and not unsigned 64-bit integers.
Therefore, we will store the data as a string.

**Comment by takuabonn** [comment]
hi, @Tejas-ChandraShekarRaju 
I have question.

When the test code is executed
 self.assertEqual(mock_insert_generated_key.call_count, 5)
AssertionError: 1 ! = 5
and it fails.
But self.assertEqual(mock_insert_generated_key.call_count, 5)
self.assertEqual(key_generator.counter, expected_counter)
succeeds.
Is there anything I can think of?

product code
```
// key_generator.py

import threading
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(ROOT_DIR)

from server.app.crud.crud import get_latest_generated_key,insert_generated_key

class KeyGenerator:
    def __init__(self):
        self.lock = threading.Lock()
        self.initial_value = None
        self.counter = 0

    def _initialize_counter(self):
        if self.initial_value is None:
            self.initial_value = get_latest_generated_key()
            self.counter = int(self.initial_value)

    def generate_key(self):
        self._initialize_counter()
        with self.lock:
            key = self.counter + 1
            print(self.counter)
            self.counter = key
            insert_generated_key(key)
            return str(key)
```
```
// crud.py

def get_latest_generated_key():
    try:
        connection = create_connection(db_file)
        cursor = connection.cursor()
        cursor.execute("""
        SELECT key FROM generated_keys ORDER BY generated_at DESC LIMIT 1;
        """, (key,))
        result = cursor.fetchone()
        if result:
            return result[0]
        else:
            return 0
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching latest key: {str(e)}")
    finally:
        connection.close()


def insert_generated_key(key):
    connection = create_connection(db_file)
    cursor = connection.cursor()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute("INSERT INTO generated_keys (key, generated_at) VALUES (?, ?)", (key, timestamp))
    connection.commit()
    connection.close()
```

test code

```
import unittest
from unittest.mock import MagicMock, patch
import os
import sys

current_dir = os.path.dirname(os.path.abspath(__file__))
key_generator_path = os.path.join(current_dir, "..", "key_generator.py")

sys.path.append(os.path.dirname(key_generator_path))

from key_generator import KeyGenerator

class KeyGeneratorTest(unittest.TestCase):
    @patch('key_generator.get_latest_generated_key', return_value=42)
    @patch('key_generator.insert_generated_key', return_value=True)
    def test_generate_key_thread_safe(self, mock_get_latest_generated_key,mock_insert_generated_key):

        key_generator = KeyGenerator()

        import threading
        NUM_THREADS = 5
        threads = []
        for _ in range(NUM_THREADS):
            t = threading.Thread(target=key_generator.generate_key)
            threads.append(t)
            t.start()
        for t in threads:
            t.join()
        
        self.assertEqual(key_generator.initial_value, 42)

        self.assertEqual(mock_insert_generated_key.call_count, 5)
        self.assertEqual(mock_get_latest_generated_key.call_count, 5)
        

        expected_counter = 42 + NUM_THREADS
        self.assertEqual(key_generator.counter, expected_counter)

```

**Comment by takuabonn** [comment]
hi, @Tejas-ChandraShekarRaju 

Please check the following pull requests.
- https://github.com/cia-labs/Storage-service/pull/31

**Comment by Tejas-ChandraShekarRaju** [comment]
> Hey @takuabonn good initial analysis. But here's what else you have to consider.
> 
> 1. Inside init - self.Counter should be taken from Sqllite3. The case here is when the server reboots the counter shouldn't start from 0, you should query the count value from Sqllite3.
> 2. Create a table in Sqllite3 key_counter and every write request should auto increment the count and use the same count.
> 3. This way our count value is persistent and every time the server reboots we'll have the latest value.
> 
> Let me know if you have any doubts.

I would like correct myself here. If you think about it. We do not need a new table. Every write request anyways writes the keys to the store table,. So we have just have to make sure our Atomic increment works well.
