### ISSUE TITLE
Upload Endpoint:

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/Storage-service#3]
1. Develop a POST endpoint /upload to receive one or multiple image files.
2. Accept optional keys associated with the images for identification.
3. Save the images in a designated folder or directory on the server.
4. Store corresponding metadata (including keys, file paths, and any additional details) in an SQLite database.

**Comment by noobed-max** [comment]
![Storage_server](https://github.com/cia-labs/Storage-service/assets/146673372/0e0d7b31-6811-47d6-a67f-850e9fd30047)

Support For Image Storage Workflow

**Comment by noobed-max** [comment]
[https://github.com/noobed-max/Temp_storageService_cheta/tree/main](https://github.com/noobed-max/Temp_storageService_cheta/tree/main)

- [ ] create directory with key and store files 
- [ ] check if key exist in the table
- [ ] auto generate key
- [ ] Retrieve multiples files
- [ ] separate db table if user wishes 
- [ ] upload endpoint done
