### ISSUE TITLE
New files uploaded with the same key are overriding the old files. 

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/Storage-service#34]
### Description:

Each value is written to a new file named encoded_text_(index_value), which means if a key "places" has four values each of those four values are written to separate files encoded_text_1, encoded_text_2 and so on. So when a new request comes in with additional values for the same category. The file names started from encoded_text_1 instead of encoded_text_5, hence replacing previously saved values.  upload method should not allow updates. Which means if a user passes the key and the key already exists we should throw and error saying key already exists and to use update. Implement this fix only in update flow

**Comment by Tejas-ChandraShekarRaju** [comment]
@noobed-max take a look at this.

**Comment by noobed-max** [comment]
to fix this bug we have to add only 
```python
# 35th line 
if check_key_existence(key):
            raise HTTPException(status_code=404, detail="Key already exist")
```
and as for the fix in update endpoint its already implemented in line 116
```python
 if path or os.path.exists(path):
        existing_files = [f for f in os.listdir(path) if f.startswith("encodedtxt")]
        if existing_files:
            max_existing_index = max(int(f.split("encodedtxt")[1].split(".")[0]) for f in existing_files)
        else:
            max_existing_index = 0

        for i, encoded_items in enumerate(encoded_content, start=max_existing_index+1):
            output_file_path = os.path.join(path, f'encodedtxt{i}.txt')

            with open(output_file_path, 'wb') as output_file:
                output_file.write(encoded_items.encode())
```

**Comment by Tejas-ChandraShekarRaju** [comment]
@noobed-max  In upload endpoint. Fix is good but 404 is not the correct response.  405 might be the correct response. 
Update can be a little more concise, You can initialise max_existing_index = 0 in the start, You can use if to update otherwise.
