### ISSUE TITLE
Retrieve Endpoint:

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/Storage-service#4]
1. Create a GET endpoint /retrieve/{key} to fetch either a single image or its metadata based on the provided key.
2. If the key is present, retrieve the associated image or metadata.
3. If no key is provided, return an appropriate error message or handle accordingly.

**Comment by noobed-max** [comment]
[https://github.com/noobed-max/Temp_storageService_cheta/tree/main](https://github.com/noobed-max/Temp_storageService_cheta/tree/main)

- [x] check if key exist in the table
- [ ] Retrieve multiples files
- [x] check separate db table if user wishes 
- [x] Retrieve endpoint done
